services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      # Database configuration
      SQLALCHEMY_DATABASE_URL: "sqlite+aiosqlite:///biodatafuse.db"
      DATABASE_URL: "sqlite:///biodatafuse.db"
      
      # CORS origins for frontend communication - use internal service communication
      CORS_ORIGINS: "http://vue-app:3000,http://localhost:3000"
      
      # API configuration
      API_HOST: "0.0.0.0"
      API_PORT: 8000
      API_RELOAD: "true"
      API_WORKERS: 1
      
      # Logging configuration
      LOG_LEVEL: "INFO"
      
      # Security settings
      SECRET_KEY: "your-secret-key-change-in-production"
      JWT_SECRET_KEY: "your-jwt-secret-key-change-in-production"
      JWT_ALGORITHM: "HS256"
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      
      # External service URLs (if needed)
      GRAPHDB_DEFAULT_URL: "http://localhost:7200"
      NEO4J_DEFAULT_URI: "bolt://localhost:7687"
      
    # Remove external port exposure - backend only accessible internally
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  vue-app:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      NODE_ENV: "development"
      
      # API URL for backend communication - use internal Docker service name
      VITE_API_URL: "http://backend:8000"
      VITE_API_BASE_URL: "http://backend:8000"
      
      # Development server configuration
      VITE_HOST: "0.0.0.0"
      VITE_PORT: 3000
      
      # Enable HTTPS in development (optional)
      HTTPS: "false"
      
      # Hot reload configuration
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      
    ports:
      - "3000:3000"  # Only expose frontend port externally
    volumes:
      - ./vue-app:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  my-volume:
